name: daos_server
servers:
- rank: null
  cpus:
  - "0"
  fabric_iface: lo
  fabric_iface_port: 31416
  log_mask: DEBUG
  log_file: ./daos_log/server.log
  env_vars:
  - ABT_ENV_MAX_NUM_XSTREAMS=100
  - ABT_MAX_NUM_XSTREAMS=100
  - DAOS_MD_CAP=1024
  - CRT_CTX_SHARE_ADDR=0
  - CRT_TIMEOUT=30
  - FI_SOCKETS_MAX_CONN_RETRY=1
  - FI_SOCKETS_CONN_TIMEOUT=2000
  - CRT_PHY_ADDR_STR=ofi+sockets
  - OFI_INTERFACE=lo
  - OFI_PORT=31416
  - D_LOG_MASK=DEBUG
  - D_LOG_FILE=./daos_log/server.log
  scm_mount: /mnt/daos
  bdev_class: nvme
  bdev_list: []
  bdev_number: 0
  bdev_size: 0
  cliopts:
  - -c
  - "1"
  - -g
  - daos_server
  - -s
  - /mnt/daos
  - -d
  - /home/jsoumagne/workspace/daos-vol/scripts
  - -i
  - "1474959424"
provider: ofi+sockets
socket_dir: /home/jsoumagne/workspace/daos-vol/scripts
access_points:
- localhost
port: 10001
ca_cert: ""
cert: ./.daos/daos_server.crt
key: ./.daos/daos_server.key
fault_path: ""
fault_cb: ""
fabric_ifaces: []
scm_mount_path: /mnt/daos
bdev_include: []
bdev_exclude: []
hyperthreads: false
nr_hugepages: 4096
control_log_mask: DEBUG
control_log_file: ./daos_log/control.log
modules: ""
attach: ""
systemmap: ""
path: /home/jsoumagne/workspace/daos-vol/scripts/daos_server_sockets.yml
nvmeshmid: 1474959424
